# Generated by Django 5.0.3 on 2024-03-23 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("Resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolved_by_technician", "Resolved by technician"),
                            ("customer_not_available", "Customer not available"),
                            ("equipment_replaced", "Equipment replaced"),
                            ("service_completed", "Service completed"),
                            ("task_canceled_by_client", "Task canceled by client"),
                            (
                                "duplicate_request",
                                "Task canceled due to duplicate request",
                            ),
                            (
                                "incorrect_information",
                                "Task canceled due to incorrect information",
                            ),
                            (
                                "lack_of_resources",
                                "Task canceled due to lack of resources",
                            ),
                            (
                                "external_factors",
                                "Task canceled due to external factors",
                            ),
                            (
                                "task_closed_without_resolution",
                                "Task closed without resolution",
                            ),
                            (
                                "transferred_to_another_team",
                                "Task transferred to another team",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
